/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ultimo;

import javax.swing.JOptionPane;


public class interfasPunto5 extends javax.swing.JFrame {
    
    int x,can1,can2,can3,can4;
    short c1,c2,c3,c4;
    String caso;
    double preciof1,preciof2,preciof3,preciof4,iva1,iva2,iva3,iva4,gana;
    

    Punto5 p1,p2,p3,p4;


    public interfasPunto5() {
        initComponents();
        
        p1= new Punto5();
        p2= new Punto5();
        p3= new Punto5();
        p3= new Punto5();
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtP1 = new javax.swing.JTextField();
        txtcantidadP1 = new javax.swing.JTextField();
        txtIva1 = new javax.swing.JTextField();
        txtprecio1 = new javax.swing.JTextField();
        txtP2 = new javax.swing.JTextField();
        txtcantidadP2 = new javax.swing.JTextField();
        txtIva2 = new javax.swing.JTextField();
        txtprecio2 = new javax.swing.JTextField();
        txtP3 = new javax.swing.JTextField();
        txtcantidadP3 = new javax.swing.JTextField();
        txtIva3 = new javax.swing.JTextField();
        txtprecio3 = new javax.swing.JTextField();
        txtP4 = new javax.swing.JTextField();
        txtcantidadP4 = new javax.swing.JTextField();
        txtIva4 = new javax.swing.JTextField();
        txtprecio4 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jButtonvender = new javax.swing.JButton();
        jButtonApartar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtGanancias = new javax.swing.JTextField();
        txtmasvendido = new javax.swing.JTextField();
        txtmenosvendido = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "producto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 0, 255))); // NOI18N

        jLabel1.setText("Producto");

        jLabel2.setText("Cantidad");

        jLabel3.setText("IVA");

        jLabel4.setText("Precio");

        txtP1.setText("computador");
        txtP1.setEnabled(false);
        txtP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtP1ActionPerformed(evt);
            }
        });

        txtcantidadP1.setText("5");
        txtcantidadP1.setEnabled(false);
        txtcantidadP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcantidadP1ActionPerformed(evt);
            }
        });

        txtIva1.setText("16.0%");
        txtIva1.setEnabled(false);
        txtIva1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIva1ActionPerformed(evt);
            }
        });

        txtprecio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtprecio1ActionPerformed(evt);
            }
        });

        txtP2.setText("Televisor");
        txtP2.setEnabled(false);
        txtP2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtP2ActionPerformed(evt);
            }
        });

        txtcantidadP2.setText("5");
        txtcantidadP2.setEnabled(false);
        txtcantidadP2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcantidadP2ActionPerformed(evt);
            }
        });

        txtIva2.setText("12.0%");
        txtIva2.setEnabled(false);

        txtP3.setText("Celular");
        txtP3.setEnabled(false);

        txtcantidadP3.setText("5");
        txtcantidadP3.setEnabled(false);

        txtIva3.setText("16.0%");
        txtIva3.setEnabled(false);

        txtP4.setText("Reproductor ");
        txtP4.setEnabled(false);

        txtcantidadP4.setText("5");
        txtcantidadP4.setEnabled(false);

        txtIva4.setText("4.0%");
        txtIva4.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtP4, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                    .addComponent(txtP3)
                    .addComponent(txtP2)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtP1))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtcantidadP4, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                            .addComponent(txtcantidadP3)
                            .addComponent(txtcantidadP2)
                            .addComponent(txtcantidadP1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtIva1)
                    .addComponent(txtIva2)
                    .addComponent(txtIva3)
                    .addComponent(txtIva4))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtprecio1)
                    .addComponent(txtprecio2)
                    .addComponent(txtprecio3)
                    .addComponent(txtprecio4, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtIva1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtcantidadP1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtP1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtprecio1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtP2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcantidadP2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIva2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtprecio2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtP3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcantidadP3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIva3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtprecio3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtP4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcantidadP4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIva4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtprecio4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "operaciones", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 0, 255))); // NOI18N

        jButtonvender.setText("Vender producto");
        jButtonvender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonvenderActionPerformed(evt);
            }
        });

        jButtonApartar.setText("Apartar producto");
        jButtonApartar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonApartarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addComponent(jButtonvender)
                .addGap(39, 39, 39)
                .addComponent(jButtonApartar)
                .addContainerGap(183, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonApartar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonvender, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "calculos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 0, 204))); // NOI18N

        jLabel5.setText("GANANCIAS");

        jLabel6.setText("P mas vendido");

        jLabel7.setText("P menos vendido");

        txtGanancias.setEnabled(false);
        txtGanancias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGananciasActionPerformed(evt);
            }
        });

        txtmasvendido.setEnabled(false);
        txtmasvendido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmasvendidoActionPerformed(evt);
            }
        });

        txtmenosvendido.setEnabled(false);
        txtmenosvendido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmenosvendidoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(50, 50, 50)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtGanancias)
                    .addComponent(txtmasvendido)
                    .addComponent(txtmenosvendido, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtGanancias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtmasvendido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtmenosvendido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtcantidadP2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcantidadP2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcantidadP2ActionPerformed

    private void jButtonvenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonvenderActionPerformed
       vender();
       comparacionMa();
       comparacionMe();
      
    }//GEN-LAST:event_jButtonvenderActionPerformed

    private void txtP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtP1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtP1ActionPerformed

    private void txtcantidadP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcantidadP1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcantidadP1ActionPerformed

    private void txtIva1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIva1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIva1ActionPerformed

    private void txtprecio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtprecio1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtprecio1ActionPerformed

    private void txtGananciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGananciasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGananciasActionPerformed

    private void txtmasvendidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmasvendidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmasvendidoActionPerformed

    private void txtmenosvendidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmenosvendidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmenosvendidoActionPerformed

    private void txtP2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtP2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtP2ActionPerformed

    private void jButtonApartarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonApartarActionPerformed
       comprar();
    }//GEN-LAST:event_jButtonApartarActionPerformed
    
    public void vender(){
    
     
   

     
     caso=JOptionPane.showInputDialog("ingresar el nombre del producto que desea comprar");
     x=Integer.parseInt(JOptionPane.showInputDialog("ingrese el numero de articulos que desea comprar"));
     
     switch(caso)
     {
     case"computador":
              p1.setCantidad(Integer.parseInt(txtcantidadP1.getText()));
              can1=p1.getCantidad()-x;
              txtcantidadP1.setText(""+can1);
            
              p1.setPrecio(Double.parseDouble(txtprecio1.getText()));
               
               iva1=(p1.getPrecio()*x)*00.16;
               preciof1=x*p1.getPrecio()+iva1;
               
               JOptionPane.showMessageDialog(null, "el costo final con iva es"+preciof1);
               
               c1++;
               
             
     
     break;
     
     case"televisor":
              p2.setCantidad(Integer.parseInt(txtcantidadP2.getText()));
               can2=p2.getCantidad()-x;
              txtcantidadP2.setText(""+can2);
              
              p2.setPrecio(Double.parseDouble(txtprecio2.getText()));
              iva2=(p2.getPrecio()*x)*00.12;
              preciof2=x*p2.getPrecio()+iva2;
               
               JOptionPane.showMessageDialog(null, "el costo final con iva es"+preciof2);
                c2++;
     
     break;
     case"celular":
              p3.setCantidad(Integer.parseInt(txtcantidadP3.getText()));
               can3=p3.getCantidad()-x;
              txtcantidadP3.setText(""+can3);
              
              p3.setPrecio(Double.parseDouble(txtprecio3.getText()));
              iva3=(p3.getPrecio()*x)*00.16;
               preciof3=x*p3.getPrecio()+iva3;
               
               JOptionPane.showMessageDialog(null, "el costo final con iva es"+preciof3);
               c3++;
     
     break;
     case"reproductor":
              p4.setCantidad(Integer.parseInt(txtcantidadP4.getText()));
               can4=p4.getCantidad()-x;
              txtcantidadP4.setText(""+can4);
             
              p4.setPrecio(Double.parseDouble(txtprecio4.getText()));
              iva4=(p4.getPrecio()*x)*00.4;
               preciof4=x*p4.getPrecio()+iva4;
               
               JOptionPane.showMessageDialog(null, "el costo final con iva es"+preciof4);
                c4++;
     
     break;
     
     default:
                 JOptionPane.showMessageDialog(null,"el caracter introducido no esta asociado a una operacion");
     
     }
        

     
     
    
    }
    
      public void comprar(){
    
     
   

     
     caso=JOptionPane.showInputDialog("ingresar el nombre del productoque desea apartar");
     x=Integer.parseInt(JOptionPane.showInputDialog("ingrese el numero de articulos que desea apartar"));
     
     switch(caso)
     {
     case"computador":
              p1.setCantidad(Integer.parseInt(txtcantidadP1.getText()));
               can1=p1.getCantidad()+x;
              txtcantidadP1.setText(""+can1);
             
              p1.setPrecio(Double.parseDouble(txtprecio1.getText()));
               
               iva1=(p1.getPrecio()*x)*00.16;
               preciof1=x*p1.getPrecio()+iva1;
               
               
               JOptionPane.showMessageDialog(null, "el costo de estos productos con iva es"+preciof1);
               
             
     
     break;
     
     case"televisor":
              p2.setCantidad(Integer.parseInt(txtcantidadP2.getText()));
              can2=p2.getCantidad()+x;
              txtcantidadP2.setText(""+can2);
              
              p2.setPrecio(Double.parseDouble(txtprecio2.getText()));
              iva2=(p2.getPrecio()*x)*00.12;
              preciof2=x*p2.getPrecio()+iva2;
               
               JOptionPane.showMessageDialog(null, "el costo de estos productos con iva es"+preciof2);
     
     break;
     case"celular":
              p3.setCantidad(Integer.parseInt(txtcantidadP3.getText()));
              can3=p3.getCantidad()+x;
              txtcantidadP3.setText(""+can3);
              
              p3.setPrecio(Double.parseDouble(txtprecio3.getText()));
              iva3=(p3.getPrecio()*x)*00.16;
               preciof3=x*p3.getPrecio()+iva3;
               
               JOptionPane.showMessageDialog(null, "el costo de estos productos con iva es"+preciof3);
     
     break;
     case"reproductor":
              p4.setCantidad(Integer.parseInt(txtcantidadP4.getText()));
              can4=p4.getCantidad()+x;
              txtcantidadP4.setText(""+can4);
             
              p4.setPrecio(Double.parseDouble(txtprecio4.getText()));
              iva4=(p4.getPrecio()*x)*00.4;
               preciof4=x*p4.getPrecio()+iva4;
               
               JOptionPane.showMessageDialog(null, "el costo de estos productos con iva es"+preciof4);
     
     break;
     
     default:
                 JOptionPane.showMessageDialog(null,"el caracter introducido no esta asociado a una operacion");
     
     }
        

     
     
    
    }
      
      public void comparacionMa(){
      
          if (c1>c2&&c1>c3&&c1>c4) {
              txtmasvendido.setText("computador");
              
          } else if(c2>c1&&c2>c3&&c4>c4){
              txtmasvendido.setText("Televisor");
              
          } else if(c3>c1&&c3>c2&&c3>c4){
              txtmasvendido.setText("Celular");
              
          } else if(c4>c1&&c4>c2&&c4>c3){
              txtmasvendido.setText("Reproductor");
          }
      
      
      
      }
      
       public void comparacionMe(){
      
          if (c1<c2&&c1<c3&&c1<c4) {
              txtmenosvendido.setText("computador");
          } else if(c2<c1&&c2<c3&&c4<c4){
              txtmenosvendido.setText("Televisor");
              
          } else if(c3<c1&&c3<c2&&c3<c4){
               txtmenosvendido.setText("Celular");
              
              
          } else if(c4<c1&&c4<c2&&c4<c3){
              txtmenosvendido.setText("Reproductor"); 
          }
      
      
      
      }
    
    
    
   
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interfasPunto5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interfasPunto5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interfasPunto5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interfasPunto5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interfasPunto5().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonApartar;
    private javax.swing.JButton jButtonvender;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField txtGanancias;
    private javax.swing.JTextField txtIva1;
    private javax.swing.JTextField txtIva2;
    private javax.swing.JTextField txtIva3;
    private javax.swing.JTextField txtIva4;
    private javax.swing.JTextField txtP1;
    private javax.swing.JTextField txtP2;
    private javax.swing.JTextField txtP3;
    private javax.swing.JTextField txtP4;
    private javax.swing.JTextField txtcantidadP1;
    private javax.swing.JTextField txtcantidadP2;
    private javax.swing.JTextField txtcantidadP3;
    private javax.swing.JTextField txtcantidadP4;
    private javax.swing.JTextField txtmasvendido;
    private javax.swing.JTextField txtmenosvendido;
    private javax.swing.JTextField txtprecio1;
    private javax.swing.JTextField txtprecio2;
    private javax.swing.JTextField txtprecio3;
    private javax.swing.JTextField txtprecio4;
    // End of variables declaration//GEN-END:variables
}
